Allow other time units in notification and scheduleddowntime
voxpupuli/puppet-icinga2 pull request #220
Opened 2017-01-28 12:21 UTC by jkroepke

Hi,

while i'm moving from the old puppet to the new, I have notice that values like 30m are not allowed anymore in some parameters.

Here is a PR for 2 cases, maybe there are a lot of more...

2017-01-28 12:49 UTC, lazyfrosch requested changes
Please update the Regexp, but thanks for noticing :+1:

2017-01-28 12:49 UTC, lazyfrosch commented on manifests/object/notification.pp
> +  if $interval { validate_re($interval, '^\d+\.?\d*[d|h|m|s]?$')}
Please use: `\d+(\.\d+)?[dhms]?`

Your syntax is not really correct, its either `(d|h|m|s)` *or* `[dhms]`

2017-01-28 12:49 UTC, lazyfrosch commented on manifests/object/scheduleddowntime.pp
> +  if $duration { validate_re($duration, '^\d+\.?\d*[d|h|m|s]?$') }
change the regexp here too

2017-01-28 12:51 UTC, jkroepke commented on manifests/object/notification.pp
> +  if $interval { validate_re($interval, '^\d+\.?\d*[d|h|m|s]?$')}
Okay, I copied it from https://github.com/Icinga/puppet-icinga2/blob/master/manifests/object/service.pp#L216 without thinking,

2017-01-28 12:54 UTC, lazyfrosch commented
I guess we should update that everywhere.

Want to do it? Would you have a look on the failing tests, or should we?

2017-01-28 12:55 UTC, lazyfrosch approved these changes

2017-01-28 12:56 UTC, jkroepke commented
> Want to do it? Would you have a look on the failing tests, or should we?
Can I look into it.

2017-01-28 13:01 UTC, jkroepke commented
@lazyfrosch 

All breakage relevant tests failed, because the error message has changed. I wound why there are test for breakage since you comment long time okay that is usually or unnecessary.

https://github.com/Icinga/puppet-icinga2-legacy/pull/169#issuecomment-177488049

2017-01-28 13:05 UTC, lazyfrosch commented
Noticed that myself while activating travis tests. Will discuss that this week with the guys.

Had similar problems with expecting for string behavior between Puppet 3+4.

Could you update the tests so:

* it tests for numeric and with suffix
* does not try to raise and test for exceptions for that params

Appreciate your help here ;)

2017-01-30 09:13 UTC, bobapple commented
Hi @jkroepke 
thanks for the effort. We should should rather change the tests where the error message has changed instead of removing them. I don't think these tests are unnecessary, they help us when editing the format of a parameter, like in this case here. I would ask you to please just change the error messages where necessary.

Please let me know if you will look into other objects, if they need this kind of updates. I just want to have a plan how we will proceed with this.

2017-02-21 08:29 UTC, merged

2017-02-21 08:31 UTC, bobapple commented
I fixed the specs and merged into master